export const LOGIN = 'LOGIN';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGOUT = 'LOGOUT';
export const PROFILE_PATIENT = 'PROFILE_PATIENT';
export const SAVE_PROFILE = 'SAVE_PROFILE';

export const LIST_FAVORITE_DOCTOR = 'LIST_FAVORITE_DOCTOR';
export const LIST_FAVORITE_CLINIC = 'LIST_FAVORITE_CLINIC';
export const SHARE_MEDICAL_DOCTOR = 'SHARE_MEDICAL_DOCTOR';
export const CANCEL_MEDICAL_DOCTOR = 'CANCEL_MEDICAL_DOCTOR';
export const ACCEPT_MEDICAL_DOCTOR = 'ACCEPT_MEDICAL_DOCTOR';
export const DENY_MEDICAL_DOCTOR = 'DENY_MEDICAL_DOCTOR';

export const REGISTER = 'REGISTER';
export const DETAIL_DOCTOR = 'DETAIL_DOCTOR';
export const CALLING_GET_ACCESS_TOKEN = 'CALLING_GET_ACCESS_TOKEN ';
export const GET_LIST_DOCTOR = 'GET_LIST_DOCTOR ';
export const GET_LIST_CLINIC = 'GET_LIST_CLINIC ';
export const NAVIGATE_TO_HOMESCREEN = 'NAVIGATE_TO_HOMESCREEN ';
export const LOADING_STATIC_DATA_DONE = 'LOADING_STATIC_DATA_DONE ';
export const BOOKING_DOCTOR = 'BOOKING_DOCTOR';
export const BOOKING_CLINIC = 'BOOKING_CLINIC';
export const CLINIC_GET_DETAIL_CLINIC = 'CLINIC_GET_DETAIL_CLINIC';
export const CLINIC_GET_DOCTOR_OF_CLINIC = 'CLINIC_GET_DOCTOR_OF_CLINIC';
export const REJECT_APPOINTMENT = 'REJECT_APPOINTMENT';

export const APPOINTMENTS_GET_LIST_FUTURE = 'APPOINTMENTS_GET_LIST_FUTURE';
export const APPOINTMENTS_GET_LIST_PAST = 'APPOINTMENTS_GET_LIST_PAST';

export const MEDICAL_HISTORY = 'MEDICAL_HISTORY';

